serverdensity/sd-agent-core-plugins

disk/conf.yaml.default
This PR excludes tmpfs from being collected and re-enables per mount metrics for disk.
@carlosperello please can you review.
=> Disk config changes

kong/CHANGELOG.md, kong/check.py, kong/manifest.json
They removed the number of items and the number of metrics in 0.11 release so we removed it from sending it which is useless.
See the difference:
* https://getkong.org/docs/0.10.x/admin-api/#retrieve-node-status
* https://getkong.org/docs/0.11.x/admin-api/#retrieve-node-status
Check the metrics sent using `sudo -u sd-agent /usr/share/python/sd-agent/agent.py check kong` before and after this change.
Use https://hub.docker.com/_/kong/ to test it out
=> Support to kong 0.11.x onwards

ceph/conf.yaml.example
This is to prevent yaml errors when a user doesn't configure tags.
=> fix example config

.travis.yml
This PR updates the travis config to use an improved for loop for the csvlint command which reduces the future maintenance burden as `SKIP_CSV_CHECK_DIRS` is no longer required. 
cc @serverdensity/backend-engineering
=> improve csvlint command

process/check.py, process/metadata.csv, process/test_process.py
This PR changes the metric name `system.processes.number` to `system.processes.instances` in the process check. 
The check, meadata and tests have all been updated. 
This is to prevent a clash with the untagged `system.processes.number` metric.
cc @serverdensity/backend-engineering
=> Update process metrics 

mysql/check.py
This PR adds the monotonic_count metric type to the MySQL check for custom query metrics.
@sixstone-qq to review please.
=> Add monotonic_count to custom query metrics

rabbitmq/CHANGELOG.md, rabbitmq/check.py, rabbitmq/manifest.json, rabbitmq/metadata.csv
Use the /api/nodes endpoint to get all cluster nodes and check if they are running. The service check fails if any node in the cluster is not running.
@pessoa
=> Add rmq cluster_status service check

kubernetes/README.md
I'm new to ServerDensity and couldn't figure out how to run `sd-agent info` on Ubuntu. I've updated the instructions so that it mentions what to do if you're on a systemd-based system.
=> Add systemd version of `sd-agent info` to the instructions

.travis/dockerfiles/bionic/entrypoint.sh, .travis/dockerfiles/jessie/entrypoint.sh, .travis/dockerfiles/stretch/entrypoint.sh, .travis/dockerfiles/trusty/entrypoint.sh, .travis/dockerfiles/xenial/entrypoint.sh, debian/changelog, debian/distros/bionic/control, debian/distros/jessie/control, debian/distros/stretch/control, debian/distros/trusty/control, debian/distros/xenial/control, packaging/el/inc/changelog, packaging/el/inc/subpackages
This PR fixes the dependency issues found with the sd-agent-cacti agent check packages during QA.
It also splits the deb build files (changelog, compat, control, rules) into per distribution folders to allow for different dependencies per distro.
=> Fix sd-agent-cacti dependencies

debian/sd-agent-pyasn1-common.install, debian/sd-agent-ssh-check.install, packaging/el/inc/install, packaging/el/inc/subpackages
This PR fixes the dependency issues found with the sd-agent-ssh-agent & sd-agent-pyasn1-common agent packages during QA.
=> Fix sd-agent-ssh-check dependencies

debian/distros/bionic/control, debian/distros/jessie/control, debian/distros/stretch/control, debian/distros/trusty/control, debian/distros/xenial/control, debian/sd-agent-ssh-check.install, packaging/el/inc/install, packaging/el/inc/subpackages, ssh_check/requirements.txt
This PR updates the paramiko dependency in the ssh-check to address CVE-2018-1000805. 
The idna module has been removed from the check as this will now be provided by agent version 2.2.2, this version of ssh-check now requires a minimum of agent 2.2.2 
Packages tested on stage and working as expected.
=> SSH-Check: Paramiko version bump

debian/distros/bionic/control, debian/distros/jessie/control, debian/distros/stretch/control, debian/distros/trusty/control, debian/distros/xenial/control, http_check/check.py, http_check/requirements.txt, packaging/el/inc/subpackages
This PR updates the requests dependency in the http-check to address CVE-2018-18074.
This version of http-check now requires a minimum of agent 2.2.2. 
Packages tested on stage and working as expected.
=> HTTP-Check: Requests version bump 

mysql/check.py
This PR adds a default timeout of 10s for the MySQL check. 
This can be overridden by users via the plugin config. 
@NassimHC please can you review/merge?
=> [MySQL] Change default connect_timeout to 10

.travis.yml, .travis/dockerfiles/bionic/entrypoint.sh, debian/changelog, debian/distros/bionic/control, debian/distros/jessie/control, debian/distros/stretch/control, debian/distros/trusty/control, debian/distros/xenial/control, debian/sd-agent-cockroachdb.install, packaging/el/inc/changelog, packaging/el/inc/install, packaging/el/inc/subpackages, packaging/el/inc/version
prometheus_client is now shipped with sd-agent and not sd-agent-cockroachdb.
Version has been bumped to v2.5.3
=> V2.5.3 - move prometheus_client to sd-agent packaging 

.travis.yml, .travis/dockerfiles/el6_i386/Dockerfile
Fixes: 
- Switched to a go implementation of csvlint ( https://github.com/Clever/csvlint/ ). The previous csvlint gem in use has dependency issues when installing.
- Updated the ius repository location to allow el6_i386 builds to complete.
@NassimHC please review and merge if happy.
=> Build fixes

.travis.yml, .travis/dockerfiles/bionic/Dockerfile, .travis/dockerfiles/bionic/entrypoint.sh, .travis/dockerfiles/buster/Dockerfile, .travis/dockerfiles/buster/entrypoint.sh, .travis/dockerfiles/stretch/Dockerfile, .travis/dockerfiles/stretch/entrypoint.sh, .travis/dockerfiles/trusty/Dockerfile, .travis/dockerfiles/trusty/entrypoint.sh, .travis/dockerfiles/xenial/Dockerfile, .travis/dockerfiles/xenial/entrypoint.sh
Enables builds for arm64 arch type on Debian and Ubuntu OS's. 
Debian Jessie was skipped as it is EoL June 30th 2020. 
Also has some .travis.yaml fixes too, as build were erroring.
=> Enable arm builds for Debian & Ubuntu

.travis/dockerfiles/el6/Dockerfile, .travis/dockerfiles/el6_i386/Dockerfile
This PR fixes an issue with el6 builds where the postgres repo config rpm was 404ing. The repo this rpm is pulled from updated the package and the name. Pointing to the correct file resolves this. 
@NassimHC please review and merge if happy and the el6 builds complete successfully (they have!).
=> Fix el6 build errors 

.travis.yml, debian/changelog, debian/distros/bionic/control, debian/distros/buster/control, debian/distros/jessie/control, debian/distros/stretch/control, debian/distros/trusty/control, debian/distros/xenial/control, debian/sd-agent-cryptography-common.install, debian/sd-agent-ssh-check.install, mysql/check.py, mysql/requirements.txt, packaging/el/inc/changelog, packaging/el/inc/subpackages, packaging/el/inc/version
This PR brings in changes to improve the compatibility of MySQL 8 with the MySQL check. 
This required a small code change from upstream and a higher version of PyMySQL. PyMySQL also wants to make use of cryptography in some instances, so sd-agent-cryptography has been created which sd-agent-mysql and sd-agent-ssh-check depend on. 
@NassimHC please can you review and merge?
=> 2.6.1 - Improve MySQL 8 Compatibility

.travis/build_containers.sh, .travis/build_packages.sh, .travis/dockerfiles/bionic/Dockerfile, .travis/dockerfiles/buster/Dockerfile, .travis/dockerfiles/el6/Dockerfile, .travis/dockerfiles/el7/Dockerfile, .travis/dockerfiles/el8/Dockerfile, .travis/dockerfiles/jessie/Dockerfile, .travis/dockerfiles/stretch/Dockerfile, .travis/dockerfiles/trusty/Dockerfile, .travis/dockerfiles/xenial/Dockerfile, debian/distros/bionic/control, debian/distros/buster/control, debian/distros/jessie/control, debian/distros/stretch/control, debian/distros/trusty/control, debian/distros/xenial/control, ntp/requirements.txt
This 'bumps' the ntplib dep to 0.3.4, however, in order to avoid binary usage I had to switch to using git in requirements.txt. 
Using master isn't an issue as ntplib is shipped in the sd-agent package as the core agent requires it, meaning the pinned version there is the version that is in use. However we need ntplib to be installed for builds to complete successfully.
@NassimHC please review and merge if happy.
=> Bump ntplib

.travis/dockerfiles/el6/Dockerfile, .travis/dockerfiles/el6_i386/Dockerfile
Updates the ius-release URLs that are used in the build containers as the redirects no longer work. 
Builds are passing with this change.
@NassimHC please review and merge if happy.
=> Update ius-release URLs for Travis Builds

.travis.yml, .travis/build_packages.sh, .travis/dockerfiles/el8/Dockerfile, README.md, debian/rules, gunicorn/ci/gunicorn.rake, packaging/el/SPECS/sd-agent-core-plugins-el6.spec, packaging/el/SPECS/sd-agent-core-plugins-el7.spec, packaging/el/SPECS/sd-agent-core-plugins-el8.spec
This PR: 
* Fixes get-pip URL for 2.7.
* Updates el8 powertools repository name.
* Removes el6 from travis config, but has not removed the files.
* Ensures ruby 2.1.5 is used. 
* Updates travis-ci badge to .com, as the repository has been migrated.
Builds have been successful on this branch and the agent has been tested to ensure that this did not inadvertently break any functionality
=> Fix get pip

.travis.yml, debian/changelog, packaging/el/inc/changelog, packaging/el/inc/version
* Bumps version to 2.6.4 and updates changelogs for mdadm and varnish plugin fixes. 
* Removes trusty from builds.
=> Version bump 2.6.4

varnish/check.py, varnish/ci/fixtures/stats_output_json_6.5
The JSON structure returned by `varnishstat -j` changed in version 6.5.
Notably, all counters have been moved under the "counters" key.
https://github.com/varnishcache/varnish-cache/blob/6.5/doc/changes.rst#varnish-cache-650-2020-09-15
----
Pulls in a commit from upstream that ensures that varnishstat 6.5 metrics are parsed correctly.
=> [varnish] fix parsing of varnishstat 6.5 JSON output 

mdadm/CHANGELOG.md, mdadm/check.py, mdadm/metadata.csv
Resolves a user reported issue with the mdadm plugin where RAID0 devices would cause the plugin to fail due to the `raid_disks` key not being present. As the `raid_disks` value is used to determine the degraded status a `system.mdadm.in_use_devices` metric was added so users can be notified if a RAID device is not present. 
Also cleans up some of the metadata.
=> [mdadm] check for presence of raid_disks / add system.mdadm.in_use_devices

debian/changelog
Updates the version number for debian builds to 2.6.4, which was missed in the previous PR.
=> Update version number to 2.6.4

.travis.yml, .travis/build_packages.sh, .travis/dockerfiles/focal/Dockerfile, .travis/dockerfiles/focal/entrypoint.sh
This PR updates the build scripts to enable aarch64/arm64 builds for Ubuntu Focal per customer requests. 
A couple of things to note: 
* The Focal container build and package build stages now run on a Focal host 
* The error `semop(1): encountered an error: Function not implemented` was seen when running the builds and prevented them from completing. To workaround this the `ppa:canonical-server/server-backports`  is added to Focal hosts which allows qemu-user-static backported from Groovy to be installed which resolves this error. [0]
* We were previously using ruby 2.1.5, however Focal does not have the correct dependencies available for this, so I bumped the Ruby version to 2.5 for everything instead of working around the dependency issue with 2.1.5 and Focal. This also allowed the rvm …
=> Enable Focal aarch64/arm64 builds 

.travis.yml, .travis/build_containers.sh, .travis/build_packages.sh, .travis/dockerfiles/bullseye/Dockerfile, .travis/dockerfiles/bullseye/entrypoint.sh, debian/distros/bullseye/control
This PR adds Debina Bullseye builds for amd64 and i386.
Packages have already been tested successfully on a local VM.
@pessoa for review please.
=> Add Debian Bullseye builds

.travis.yml, .travis/dockerfiles/el7_arm/Dockerfile, .travis/dockerfiles/el7_arm/entrypoint.sh, .travis/dockerfiles/el8/Dockerfile, .travis/dockerfiles/el8_arm/Dockerfile, .travis/dockerfiles/el8_arm/entrypoint.sh, packaging/el/SPECS/sd-agent-core-plugins-el7.spec, packaging/el/SPECS/sd-agent-core-plugins-el8.spec
This PR:
* Fixes an error in the el8 build containers.
* Adds packaging for aarch64 for el7/8
* Removes the BuildArch from the el SPEC files as the build arch is implied from the build container's arch.
* Adds travis_wait to all script commands as the el containers do not output anything for over 10mins (causing the build to be deemed failed) despite still running.
=> Add El ARM Packaging

.travis.yml, debian/changelog, packaging/el/inc/changelog, packaging/el/inc/version, process/check.py
Adds `process:$process` tag to ensure that process alerts trigger.
Bumps version to 2.6.5 for release.
=> Ensure process alerts trigger

.travis.yml, .travis/build_containers.sh, .travis/build_packages.sh, .travis/dockerfiles/jammy/Dockerfile, .travis/dockerfiles/jammy/entrypoint.sh, debian/distros/jammy/control, debian/distros/jammy/rules, debian/distros/jammy/sd-agent-cryptography-common.install, debian/distros/jammy/sd-agent-pyasn1-common.install
This PR adds Jammy/Ubuntu 22 builds to travis.
* Had to bump cryptography for the build to succeed which was done via the rules, this changed the contents of the sd-agent-cryptography-common and sd-agent-pyasn1-common packages. 
* Had to make use of gzip compression instead of the standard zstd to allow the repo creation automation to complete.
=> Add Jammy/Ubuntu 22 builds

.travis.yml, mysql/check.py
This PR updates the MySQL plugin to handle the updated output from "SHOW ENGINE INNODB STATUS" in MariaDB 10.10. 
Tested with no issues on MariaDB 10.10 & 10.8.7, and MySQL 5.7.38.
@pessoa to review
=> Fix MariaDB innodb status check parsing

.travis.yml
This PR removes Jessie builds from the Travis config.
Jessie is EoL for years and the builds are now failing. We have old builds and will preserve an old version of the agent for Jessie in the repos, per other EoL OS. 
@pessoa to review.
=> Remove jessie builds

.travis.yml, debian/changelog, packaging/el/inc/changelog, packaging/el/inc/version
This PR bumps the packaging version to 2.6.7, ready for release. 
Ideally this should be merged last, after #75 and #76 
@pessoa to review
=> Bump version to 2.6.7
